import Image from "next/image";
import Link from "next/link";
import {ArrowDown,ArrowRight,ArrowUpRight,Check,Mail,MapPin,PackageCheck,Phone} from "lucide-react";
import {ProductCard} from "@/components/product-card";
import {products,services,site} from "@/lib/site";

export function Hero(){return <section className="relative min-h-[calc(100svh-76px)] overflow-hidden bg-[#101a32] text-white"><Image src="/images/lixiang-hero.png" alt="Container port and global goods movement" fill priority className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,18,43,.96)_0%,rgba(9,18,43,.78)_47%,rgba(9,18,43,.18)_100%)]"/><div className="container-page relative flex min-h-[calc(100svh-76px)] flex-col justify-between py-9 sm:py-12"><div className="flex items-start justify-between gap-5"><p className="eyebrow text-[#ff7a61]">Ontario / Cross-border trade</p><p className="eyebrow hidden sm:block">Manifest No. LX-2026-01</p></div><div className="grid gap-8 lg:grid-cols-[1fr_19rem] lg:items-end"><div><p className="eyebrow mb-5">Product programs for retail + distribution</p><h1 className="max-w-5xl text-[clamp(3.4rem,9vw,8.8rem)] font-black uppercase leading-[.78]">Goods in motion.<br/><span className="text-[#ff654e]">Markets in reach.</span></h1></div><div className="bg-[#f4f0e8] p-5 text-black"><div className="flex justify-between border-b border-black pb-3"><p className="eyebrow">Trade brief</p><p className="mono text-xs">01/10</p></div><dl className="mt-4 grid grid-cols-[5rem_1fr] gap-y-3 text-xs"><dt className="font-bold">ORIGIN</dt><dd>Ontario, CA</dd><dt className="font-bold">SCOPE</dt><dd>Multi-category</dd><dt className="font-bold">MODEL</dt><dd>Buyer-led programs</dd></dl><Link href="/contact" className="mt-5 flex items-center justify-between bg-[#1746a2] px-4 py-3 text-xs font-black uppercase tracking-[.12em] text-white">Send brief <ArrowUpRight size={15}/></Link><div className="barcode mt-5 h-8"/></div></div><div className="flex items-center justify-between border-t border-white/30 pt-5"><p className="eyebrow text-white/55">Sourcing / assortment / packaging / supply</p><ArrowDown size={18}/></div></div></section>}

export function Manifest(){return <section className="paper-grid bg-[#f4f0e8] py-24 sm:py-32"><div className="container-page"><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-[#f04b35]">Manifest / 01</p><p className="mt-6 text-8xl font-black leading-none text-[#1746a2]">10</p><p className="mt-2 text-sm font-bold uppercase">Product directions</p></div><div><h2 className="max-w-5xl text-5xl font-black uppercase leading-[.9] sm:text-7xl">A flexible catalog for buyers who know their market.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-black/60">LIXIANG Trade develops focused consumer-goods programs around a buyer brief, channel requirements, packaging needs, and commercial timing.</p><div className="mt-12 border-t-2 border-black">{products.slice(0,5).map((product,index)=><div key={product.name} className="grid grid-cols-[3rem_1fr_auto] items-center gap-3 border-b border-black/30 py-4"><p className="mono text-xs text-[#f04b35]">{String(index+1).padStart(2,"0")}</p><h3 className="font-black uppercase">{product.name}</h3><p className="eyebrow hidden text-black/50 sm:block">{product.category}</p></div>)}</div></div></div></div></section>}

export function ProductDispatch(){return <section className="bg-[#fffdf7] py-24 sm:py-32"><div className="container-page"><div className="flex items-end justify-between gap-8 border-b-2 border-black pb-7"><div><p className="eyebrow text-[#1746a2]">Catalog release / 02</p><h2 className="mt-4 text-5xl font-black uppercase sm:text-7xl">Ready to be shaped.</h2></div><Link href="/showcase" className="hidden items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#f04b35] sm:flex">View all lots <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,8).map((product,index)=><ProductCard key={product.name} product={product} index={index}/>)}</div></div></section>}

export function TradeRoute(){const steps=[["01","Brief","Category, market, target and quantity."],["02","Source","Supplier direction and product fit."],["03","Sample","Review, refine and confirm details."],["04","Prepare","Packaging and program readiness."],["05","Coordinate","Commercial timing and supply flow."]];return <section className="bg-[#1746a2] py-24 text-white sm:py-32"><div className="container-page"><div className="grid gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p className="eyebrow text-[#ff7a61]">Trade route / 03</p><PackageCheck className="mt-7" size={48}/></div><div><h2 className="max-w-4xl text-5xl font-black uppercase leading-[.9] sm:text-7xl">From request to ready.</h2><div className="route-line mt-14 h-1"/><div className="grid md:grid-cols-5">{steps.map(([id,title,text])=><div key={id} className="border-b border-white/25 py-6 md:border-b-0 md:border-r md:px-4 md:first:pl-0 md:last:border-r-0"><p className="mono text-xs text-[#ff7a61]">{id}</p><h3 className="mt-6 text-xl font-black uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></div>)}</div></div></div></div></section>}

export function ContactSection(){return <section className="bg-[#f4f0e8] py-24 sm:py-32"><div className="container-page grid border-2 border-black lg:grid-cols-[.75fr_1.25fr]"><div className="bg-[#f04b35] p-7 text-white sm:p-10"><p className="eyebrow">Buyer inquiry / Form LX-04</p><h1 className="mt-8 text-5xl font-black uppercase leading-[.88] sm:text-7xl">What should move next?</h1><p className="mt-7 max-w-md text-lg leading-8 text-white/75">Share the category, market, target quantity, or packaging need. A useful trade conversation starts with a clear brief.</p><div className="mt-10 grid gap-4 text-sm font-bold"><a href={`mailto:${site.email}`} className="flex items-center gap-3"><Mail size={18}/>{site.email}</a><a href={`tel:${site.phoneHref}`} className="flex items-center gap-3"><Phone size={18}/>{site.phone}</a><p className="flex items-center gap-3"><MapPin size={18}/>{site.address.city}, Canada</p></div></div><form className="bg-[#fffdf7] p-7 sm:p-10"><div className="flex items-center justify-between border-b-2 border-black pb-4"><p className="eyebrow">Product brief</p><p className="mono text-xs">REF / NEW</p></div><div className="mt-7 grid gap-x-8 sm:grid-cols-2"><label className="eyebrow">Name<input className="inquiry-input" aria-label="Name"/></label><label className="eyebrow mt-6 sm:mt-0">Business email<input className="inquiry-input" aria-label="Business email" type="email"/></label></div><label className="eyebrow mt-7 block">Category or product<input className="inquiry-input" aria-label="Category or product"/></label><label className="eyebrow mt-7 block">Market, quantity and timing<textarea className="inquiry-input min-h-28 resize-none" aria-label="Market, quantity and timing"/></label><Link href={`mailto:${site.email}?subject=LIXIANG%20Trade%20Product%20Brief`} className="mt-8 flex w-full items-center justify-between bg-black px-6 py-5 text-xs font-black uppercase tracking-[.14em] text-white transition hover:bg-[#1746a2]">Submit product brief <ArrowUpRight size={17}/></Link></form></div></section>}

export function ProductGrid({limit}:{limit?:number}){const visible=limit?products.slice(0,limit):products;return <section className="bg-[#fffdf7] py-20"><div className="container-page grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{visible.map((product,index)=><ProductCard key={product.name} product={product} index={index}/>)}</div></section>}
export function TrustBand(){return <Manifest/>}
export function ServicesSection(){return <TradeRoute/>}
